
class Define():
    WINDOWS_8 = 1
    WINDOWS_SERVER_2012 = 2
    WINDOWS_10 = 3
    WINDOWS_SERVER_2016 = 4

    RAID_LEVEL_SIMPLE = 5
    RAID_LEVEL_2MIRROR = 6
    RAID_LEVEL_3MIRROR = 7
    RAID_LEVEL_PARITY = 8